config/routes.rb
Rails.application.routes.draw do
  resources :carousels

  get 'store/index'

  resources :products

   root 'store#index', as: 'store'

end

app/models/carousel.rb
class Carousel < ActiveRecord::Base
end

app/models/product.rb
class Product < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/carousels_controller.rb
class CarouselsController < ApplicationController
  before_action :set_carousel, only: [:show, :edit, :update, :destroy]

  # GET /carousels
  # GET /carousels.json
  def index
    @carousels = Carousel.all
  end

  # GET /carousels/1
  # GET /carousels/1.json
  def show
  end

  # GET /carousels/new
  def new
    @carousel = Carousel.new
  end

  # GET /carousels/1/edit
  def edit
  end

  # POST /carousels
  # POST /carousels.json
  def create
    @carousel = Carousel.new(carousel_params)

    respond_to do |format|
      if @carousel.save
        format.html { redirect_to @carousel, notice: 'Carousel was successfully created.' }
        format.json { render :show, status: :created, location: @carousel }
      else
        format.html { render :new }
        format.json { render json: @carousel.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carousels/1
  # PATCH/PUT /carousels/1.json
  def update
    respond_to do |format|
      if @carousel.update(carousel_params)
        format.html { redirect_to @carousel, notice: 'Carousel was successfully updated.' }
        format.json { render :show, status: :ok, location: @carousel }
      else
        format.html { render :edit }
        format.json { render json: @carousel.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carousels/1
  # DELETE /carousels/1.json
  def destroy
    @carousel.destroy
    respond_to do |format|
      format.html { redirect_to carousels_url, notice: 'Carousel was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_carousel
      @carousel = Carousel.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def carousel_params
      params.require(:carousel).permit(:headline, :note, :textbutton, :image)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :description, :size, :price, :image)
    end
end

app/controllers/store_controller.rb
class StoreController < ApplicationController
  def index
  	@products = Product.order(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carousels_helper.rb
module CarouselsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/store_helper.rb
module StoreHelper
end

app/views/carousels/_form.html.erb
<%= form_for(@carousel) do |f| %>
  <% if @carousel.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@carousel.errors.count, "error") %> prohibited this carousel from being saved:</h2>

      <ul>
      <% @carousel.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :headline %><br>
    <%= f.text_field :headline %>
  </div>
  <div class="field">
    <%= f.label :note %><br>
    <%= f.text_area :note %>
  </div>
  <div class="field">
    <%= f.label :textbutton %><br>
    <%= f.text_field :textbutton %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.text_field :image %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/carousels/edit.html.erb
<h1>Editing Carousel</h1>

<%= render 'form' %>

<%= link_to 'Show', @carousel %> |
<%= link_to 'Back', carousels_path %>

app/views/carousels/index.html.erb
<h1>Listing carousel</h1>
<table>
<% @carousels.each do |carousel| %>
<tr class="<%= cycle('list_line_odd', 'list_line_even') %>">
<td>
<%= image_tag(carousel.image, class: 'list_image') %>
</td>
<td class="list_description">
<dl>
<dt><%= carousel.headline %></dt>
<dd><%= truncate(strip_tags(carousel.note), length: 80) %></dd>
</dl>
</td>
<td class="list_actions">
<%= link_to 'Show', carousel %><br/>
<%= link_to 'Edit', edit_carousel_path(carousel) %><br/>
<%= link_to 'Destroy', carousel, method: :delete,
data: { confirm: 'Are you sure?' } %>
</td>
</tr>
<% end %>
</table>
<br />

<%= link_to 'New Carousel', new_carousel_path %>

app/views/carousels/new.html.erb
<h1>New Carousel</h1>

<%= render 'form' %>

<%= link_to 'Back', carousels_path %>

app/views/carousels/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Headline:</strong>
  <%= @carousel.headline %>
</p>

<p>
  <strong>Note:</strong>
  <%= @carousel.note %>
</p>

<p>
  <strong>Textbutton:</strong>
  <%= @carousel.textbutton %>
</p>

<p>
  <strong>Image:</strong>
  <%= @carousel.image %>
</p>

<%= link_to 'Edit', edit_carousel_path(@carousel) %> |
<%= link_to 'Back', carousels_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tshop</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body class='<%= controller.controller_name %>'>
<%= yield %>

</body>
</html>

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description, rows: 6 %>
  </div>
  <div class="field">
    <%= f.label :size %><br>
    <%= f.text_field :size %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.text_field :image %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<h1>Listing products</h1>
<table>
  <% @products.each do |product| %>
    <tr class="<%= cycle('list_line_odd', 'list_line_even') %>">
      <td>
        <%= image_tag(product.image, class: 'list_image') %>
      </td>
      <td class="list_description">
        <dl>
          <dt><%= product.name %></dt>
          <dd><%= truncate(strip_tags(product.description), length: 80) %></dd>
        </dl>
      </td>
      <td class="list_actions">
        <%= link_to 'Show', product %><br/>
        <%= link_to 'Edit', edit_product_path(product) %><br/>
        <%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %>
      </td>
    </tr>
  <% end %>
</table>
<br />
<%= link_to 'New product', new_product_path %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<p>
  <strong>Size:</strong>
  <%= @product.size %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<p>
  <strong>Image:</strong>
  <%= @product.image %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>

app/views/store/index.html.erb
<body>
<div class="navbar-wrapper">
	<div class="container">
        <nav class="navbar navbar-inverse navbar-static-top">
    		<div class="navbar-header">
            	<a class="navbar-brand" href="#">Tshop</a>
            </div>
            <div id="navbar" class="navbar-collapse collapse">
            	<ul class="nav navbar-nav">
                	<li class="active"><a href="#">Home</a></li>
                	<li class="dropdown">
                  		<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">NEW PRODUCT <span class="caret"></span></a>
                		<ul class="dropdown-menu" role="menu">
                			<li class="dropdown-header">Nav header</li>
                			<li class="divider"></li>
                    		<li><a href="#">Action</a></li>
                    		<li><a href="#">Action</a></li>
                    		<li><a href="#">Action</a></li>
                		</ul>
                	</li>
                	<li class="dropdown">
                  		<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">SHOP <span class="caret"></span></a>
                		<ul class="dropdown-menu" role="menu">
                			<li class="dropdown-header">Nav header</li>
                			<li class="divider"></li>
                    		<li><a href="#">Action</a></li>
                    		<li><a href="#">Action</a></li>
                    		<li><a href="#">Action</a></li>
                		</ul>
                	</li>
                	<li class="dropdown">
                  		<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">PAGE <span class="caret"></span></a>
                		<ul class="dropdown-menu" role="menu">
                			<li class="dropdown-header">Nav header</li>
                			<li class="divider"></li>
                    		<li><a href="#">Action</a></li>
                    		<li><a href="#">Action</a></li>
                    		<li><a href="#">Action</a></li>
                		</ul>
                	</li>
            	</ul>
            </div>
        </nav>
	</div>
</div>

<div id="myCarousel" class="carousel slide" data-ride="carousel">
      <!-- Indicators -->
      <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1" class=""></li>
        <li data-target="#myCarousel" data-slide-to="2" class=""></li>
      </ol>
      <div class="carousel-inner" role="listbox">
        <div class="item active">
          <img class="first-slide" src="http://codepeoples.com/tanimdesign.net/thsop-v-1.3/white/images/slider/slider0.jpg" alt="First slide">
          <div class="container">
            <div class="carousel-caption">
              <h1>Example headline.</h1>
              <p>Note: If you're viewing this page via a <code>file://</code> URL, the "next" and "previous" Glyphicon buttons on the left and right might not load/display properly due to web browser security rules.</p>
              <p><a class="btn btn-lg btn-primary" href="#" role="button">Sign up today</a></p>
            </div>
          </div>
        </div>
        <div class="item">
          <img class="second-slide" src="http://codepeoples.com/tanimdesign.net/thsop-v-1.3/white/images/slider/slider3.jpg" alt="Second slide">
          <div class="container">
            <div class="carousel-caption">
              <h1>Another example headline.</h1>
              <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
              <p><a class="btn btn-lg btn-primary" href="#" role="button">Learn more</a></p>
            </div>
          </div>
        </div>
        <div class="item">
          <img class="third-slide" src="http://codepeoples.com/tanimdesign.net/thsop-v-1.3/white/images/slider/slider0.jpg" alt="Third slide">
          <div class="container">
            <div class="carousel-caption">
              <h1>One more for good measure.</h1>
              <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
              <p><a class="btn btn-lg btn-primary" href="#" role="button">Browse gallery</a></p>
            </div>
          </div>
        </div>
      </div>
    </div>




















<div class="row">
	<% @products.each do |product| %>
		<div class="item col-lg-3 col-md-3 col-sm-4 col-xs-6">
			<div class="eachproduct">
        		<div class="image">  
        			<%= image_tag(product.image) %>
            	</div>
            	<div class="description">
              		<h4><a href="product-details.html"><%= product.name %></a></h4>
              		<p><%= sanitize(product.description) %></p>
              		<span class="size"><%= product.size %></span> 
            	</div>
            	<div class="price"<span class="price"><%= product.price %></span> </div>
            	<div class="action-control"> <a class="btn btn-primary"> <span class="add2cart"><i class="glyphicon glyphicon-shopping-cart"> </i> Add to cart </span> </a> </div>
        	</div>
		</div>
		<div class="item col-lg-3 col-md-3 col-sm-4 col-xs-6">
			<div class="eachproduct">
        		<div class="image">  
        			<%= image_tag(product.image) %>
            	</div>
            	<div class="description">
              		<h4><a href="product-details.html"><%= product.name %></a></h4>
              		<p><%= sanitize(product.description) %></p>
              		<span class="size"><%= product.size %></span> 
            	</div>
            	<div class="price"<span class="price"><%= product.price %></span> </div>
            	<div class="action-control"> <a class="btn btn-primary"> <span class="add2cart"><i class="glyphicon glyphicon-shopping-cart"> </i> Add to cart </span> </a> </div>
        	</div>
		</div>
		<div class="item col-lg-3 col-md-3 col-sm-4 col-xs-6">
			<div class="eachproduct">
        		<div class="image">  
        			<%= image_tag(product.image) %>
            	</div>
            	<div class="description">
              		<h4><a href="product-details.html"><%= product.name %></a></h4>
              		<p><%= sanitize(product.description) %></p>
              		<span class="size"><%= product.size %></span> 
            	</div>
            	<div class="price"<span class="price"><%= product.price %></span> </div>
            	<div class="action-control"> <a class="btn btn-primary"> <span class="add2cart"><i class="glyphicon glyphicon-shopping-cart"> </i> Add to cart </span> </a> </div>
        	</div>
		</div>
		<div class="item col-lg-3 col-md-3 col-sm-4 col-xs-6">
			<div class="eachproduct">
        		<div class="image">  
        			<%= image_tag(product.image) %>
            	</div>
            	<div class="description">
              		<h4><a href="product-details.html"><%= product.name %></a></h4>
              		<p><%= sanitize(product.description) %></p>
              		<span class="size"><%= product.size %></span> 
            	</div>
            	<div class="price"<span class="price"><%= product.price %></span> </div>
            	<div class="action-control"> <a class="btn btn-primary"> <span class="add2cart"><i class="glyphicon glyphicon-shopping-cart"> </i> Add to cart </span> </a> </div>
        	</div>
		</div>
	<% end %>
</div>

</body>